### ISSUE TITLE
How to use with vmess subscription?

### ISSUE THREAD

**Issue by ZhiyuanChen** [zw963/asuswrt-merlin-v2ray#2]
Thank you for this awesome project. 

I noticed that it has some scripts for setting up VPS and router, is there any instruction for vmess subscription?

**Comment by zw963** [comment]
Check https://github.com/zw963/asuswrt-merlin-v2ray/blob/master/deploy_server#L133-L387

And https://github.com/zw963/asuswrt-merlin-v2ray/blob/master/v2ray_server.json

for the first deploy_server one, because xray and v2ray use same script, the default generated is for xray, if you want use v2ray, have to do some replace. like this:  https://github.com/zw963/asuswrt-merlin-v2ray/blob/master/deploy_server#L389-L398
